language: c

env:
  - LUA_VERSION=5.2

branches:
  only:
    - master

install:
  - sudo apt-get update
  - sudo apt-get install lua5.2
  - sudo apt-get install liblua5.2-dev
  - sudo apt-get install luarocks
  - chmod +x travis.sh
  - ./travis.sh
  - sudo luarocks install busted
      
script: make && make DIALOGUE_HEADLESS=true check

notifications:
  recipients:
    - leroy@bythehilt.com
  email:
    on_success: change
    on_failure: always
