language: c

env:
  - LUA_VERSION=5.2

branches:
  only:
    - master

before_install:
  - chmod +x travis.sh
  - ./travis.sh

install:
  - sudo apt-get install luarocks
  - sudo luarocks install busted

script: make

notifications:
  recipients:
    - leroy@bythehilt.com
  email:
    on_success: change
    on_failure: always
