language: c

env:
  - LUA_VERSION=5.2

before_install:
  - chmod +x travis.sh
  - ./travis.sh

script: make && make test

notifications:
  recipients:
    - leroy@bythehilt.com
  email:
    on_success: change
    on_failure: always
