language: c

env:
  - LUA_VERSION=5.2

branches:
  only:
    - master
    - travis

install:
  - sudo apt-get install lua5.2
  - sudo apt-get install liblua5.2-dev
  - sudo apt-get install luarocks
  - sudo luarocks install busted
  - lua -v
  - sudo find / -name "lua.h"
  - busted --version

script: make travis_build && make test

notifications:
  recipients:
    - leroy@bythehilt.com
  email:
    on_success: change
    on_failure: always
