language: c

env:
  - LUA="Lua 5.2"

install:
  - sudo apt-get install lua5.2
  - sudo apt-get install luarocks
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted

script: make && make test

notifications:
  recipients:
    - leroy@bythehilt.com
  email:
    on_success: change
    on_failure: always
