language: c

env:
  - LUA="Lua 5.2"
  - LUA_VERSION=5.2

before_install:
  - ./travis.sh

install:
  - sudo apt-get install luarocks
  - sudo luarocks install busted

script: make && make test

notifications:
  recipients:
    - leroy@bythehilt.com
  email:
    on_success: change
    on_failure: always
